#!/usr/bin/python3
def raise_exception():
    a = "prueba"
    b = 1
    result = a + b
